### ISSUE TITLE
Filter randomly stopped working? (v5.1.1)

### ISSUE THREAD

**Issue by Balduranne** [rthaut/deviantART-Filter#102]
I'm running Firefox Quantum 68.0b6 64x (Apparently?), and for some reason my tag filters are no longer working. They're still in my filter, but I see deviations with said tags in my search/browsing. 

Strangely, it filters out users normally, so I'm not sure what's going on.

And while I have the opportunity, I'd like to thank you for this tool. DeviantART is full of disgusting shit, and I can't imagine browsing it without any aggressive filters anymore.

**Comment by rthaut** [comment]
Duplicate of #58 

@Balduranne thanks for the report. You should be able to "fix" the tag filters by setting the "Number of Days to Cache Metadata" setting to 0 (which will clear the cache), and then after restarting FF you can change that setting back to the original value.
