### ISSUE TITLE
6.0.0: Deviations are filtered on Notifications page 

### ISSUE THREAD

**Issue by luckysgb** [rthaut/deviantART-Filter#133]
deviantART-Filter 6.0.0 is filtering deviations from filtered users on the Notifications page. This did not occur in previous versions. The "deviation stacks" themselves are not filtered, but individual deviations are (including those within the stacks). Seems to affect both Eclipse and the old design.

I consider this behavior to be undesirable because I only use the addon to filter deviations from my watched users (to avoid seeing them again, such as in other users' Favorites). If this behavior is desired by some deviantART-Filter users, adding an "enable/disable filtering on Notifications page" option would be ideal.

Browser: Waterfox 2020.04

**Comment by rthaut** [comment]
Over the years I have had many requests for the filters to work on **more** pages, and the Notifications page was almost always mentioned specifically. I wanted to get version 6.0.0 shipped before DeviantArt forced everyone to switch to Eclipse later this month, and in my rush it never occurred to me that people probably liked it **not** working on the Notifications page.

> adding an "enable/disable filtering on Notifications page" option would be ideal

This is a great suggestion. I will plan to include it in the next release (v6.1.0), barring any technical issues that make it unreasonably difficult to implement.

**Comment by luckysgb** [comment]
Looks good! Thank you for this change.
