### ISSUE TITLE
Option in right click menu to block username in one click

### ISSUE THREAD

**Issue by kargaroc** [rthaut/deviantART-Filter#148]
This is a lovely plugin, and quite easy to use, but sometimes there's just too many things you want to block.
It's tedious to go through entire pages of spam, blocking users one by one.
Of course, you're always gonna have to do that - but it would be much faster if I could bypass the "create filter from this deviation" window.  It's a useful window, but in cases where I know that I just want to block an account (ie, spammers), it slows me down.

An option to block accounts that is directly in the right click menu would be the perfect way to do this.
Something like [this](https://i.imgur.com/H053vbO.png).

**Comment by rthaut** [comment]
This will be available in version 6.2, which I hope to release this weekend.

However, if an extension has 2 or more context menus, browsers automatically group them into a sub-menu.

Firefox:
![Firefox](https://user-images.githubusercontent.com/5234749/133870583-885f0b6e-e582-45d7-8564-160ae38d848f.png)

Chrome:
![Chrome](https://user-images.githubusercontent.com/5234749/133870586-4c414e8b-6c4f-4062-ac25-46535d3a56bc.png)
