### ISSUE TITLE
Dark Mode disabled itself, cannot reactivate it

### ISSUE THREAD

**Issue by McBobb** [rthaut/deviantART-Filter#192]
As of Feb 12, 2022, the DeviantArt Filter Manager page suddenly no longer displayed in dark mode, as I had set it, and clicking the button to switch back to dark mode does nothing. I'm using the previous version of Firefox because there are serious, showstopper-level problems with the newest version of Firefox for Windows, but I have the most recent version of the addon.

Windows 10 Home 64 bit
Firefox x64 96.0.3 (v. 97 is unusuable)
DeviantART Filter 6.2.0

**Comment by rthaut** [comment]
I have not been able to reproduce this yet on a virtual machine with Windows 10 and Firefox 96. Are you still having the issue?

If so, do you have any other extensions installed that might set/override your dark mode preferences, or any extensions that disable/change local storage?

This extension is supposed to check if you have previously enabled (or enabled then disabled) Dark Mode through the toggle button, and, if not, it checks your system/browser preference to figure out a default. Once you use the toggle button, it saves your preference in local browser storage.

**Comment by McBobb** [comment]
The bug was with that release of Firefox. When the next version of Firefox was available and I installed it, the issue went away.

Thanks
