### ISSUE TITLE
Incompatible with New Thumbnail Grid

### ISSUE THREAD

**Issue by rthaut** [rthaut/deviantART-Filter#4]
The [new thumbnail grid](http://danlev.deviantart.com/journal/New-Thumbnail-Grid-Launched-To-All-Deviants-608840160) has significantly changed the DOM structure.

Thumbnails no longer have username or userid attributes, nor do they contain any category data.

**Comment by timeless00** [comment]
Is it possible to get the info from the url itself? Thumbnails should still have that username inside the url.

**Comment by lassekongo83** [comment]
I solved this in my Stylish userstyle by pulling the username from the span's href with a wildcard like this:
`span[href*="horribleusername"]`

**Comment by rthaut** [comment]
The rewrite is basically complete (https://github.com/rthaut/deviantART-Filter/tree/feature-new-thumbnails), but there is an issue when blocking new users from the "x" icon on their deviation thumbnails.

I don't think category filtering will be re-implemented; none of the category data is exposed in the DOM.
