### ISSUE TITLE
Supporting Filtering Deviations by Title

### ISSUE THREAD

**Issue by rthaut** [rthaut/deviantART-Filter#49]
Add support for filtering deviations based on their titles via keyword matching (similar to tag filters).

This could be implemented either by creating an option that causes tag filters to also be applied to titles, or it could be maintained as a separate list of filters.

Most likely this will be implemented as the former, as that is a simpler solution and would prevent users from having to maintain to separate keyword lists (assuming the normal use case is to want to filter certain words in BOTH the tags and the title).

It may be appropriate to rename Tag filters to Keyword filters, and have settings to control against which "fields" the keyword filters are applied (i.e. tags, titles, or both).

**Comment by A-Really-Big-Cat** [comment]
I really want this! Deviantart is such a cesspool and most users don't tag their deviations. You could also use this approach for descriptions as well.
