### ISSUE TITLE
Add a Context Menu for Filtering Tags from Links

### ISSUE THREAD

**Issue by Kimed** [rthaut/deviantART-Filter#59]
Hello, and thanks for a great addon. Finally I can skip on all those [filtered] as if they never were there (^_^)_b. I have a small request, though. Would it be possible for the addon to recognize mouse right-clicks when a dA page is open, and if the target is a https://www.deviantart.com/tag/something kind of link, add an "Add #something to the list of blocked tags" option to the context menu. That would make using the addon so much easier.

Thank you.

**Comment by rthaut** [comment]
This seems like a great enhancement. I think it also makes sense to do the same thing for category links.

For my reference (or anyone else what wants to work on this feature), it looks like using the [`targetUrlPatterns`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create) property when creating/registering the menu should allow us to only target links for tags and/or categories.

**Comment by rthaut** [comment]
> I think it also makes sense to do the same thing for category links.

Eclipse doesn't seem to have links to specific categories anymore. Instead, there are links to "topics" which seem related to categories but do **not** seem to have hierarchy data (and thus do not really correspond to paths used by category filters).

For v6.0.0,0 I think I am only going to ship this functionality for tags (as originally requested), although it can certainly be revisited and/or expanded upon in the future.
